version: "3.9"

services:
  # =========================
  # SEAWEEDFS MASTER
  # =========================
  master:
    image: chrislusf/seaweedfs
    command:
      [
        "master",
        "-mdir=/master",
        "-ip=master",
        "-defaultReplication=000",
        "-volumeSizeLimitMB=30000",
      ]
    ports:
      - "9333:9333"
      - "19333:19333"
    volumes:
      - ./data/seaweed/master:/master
    restart: unless-stopped

  # =========================
  # SEAWEEDFS VOLUME
  # =========================
  volume:
    image: chrislusf/seaweedfs
    command:
      [
        "volume",
        "-mserver=master:9333",
        "-dir=/data",
        "-publicUrl=${SEAWEED_PUBLIC_URL}",
        "-ip=volume",
        "-port=8083",
      ]
    ports:
      - "8083:8083"
    volumes:
      - ./data/seaweed/volume:/data
    restart: unless-stopped

  # =========================
  # POSTGRES
  # =========================
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: share2teach_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d share2teach_db"]
      interval: 5s
      timeout: 35s
      retries: 11
    restart: unless-stopped

  # =========================
  # SPRING BOOT
  # =========================
  spring:
    build:
      context: ../share2teach
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres:5432/share2teach_db
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}

      SEAWEED_MASTER_URL: http://master:9333

      SERVER_PORT: 8081
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS} # Changed from hardcoded value
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8081/actuator/health"]
      interval: 5s
      timeout: 40s
      retries: 10

  # =========================
  # NGINX REVERSE PROXY
  # =========================
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      spring:
        condition: service_healthy
